Vagrant.configure("2") do |config|
    boxes = [
      { :name => "ubu", :box => "generic/ubuntu1804" },
      { :name => "c7", :box => "generic/centos7" }
    ]
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.box = opts[:box]
        if opts[:name] == boxes.last[:name]
          config.vm.provision "ansible" do |ansible|
            ansible.playbook = "test.yml"
            ansible.limit = "all"
          end
        end
      end
    end
  end

