# tasks file for install_nginx
- name: Change repos on redhat
  shell: "sed 's/^mirrorlist.*//g' /etc/yum.repos./dCentOS-Base.repo -i ; sed 's/#baseurl/baseurl/g' /etc/yum.repos.d/CentOS-Base.repo -i" 



- name: Ensure if Nginx presents
  yum:
    name: nginx
    state: present
  notify: start nginx  

- name: Copy nginx.conf to destination
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  notify: reload nginx

- name: stop firewalld
  service:
    name: firewalld
    state: stopped

